# WARNING - Generated by {fusen} from /dev/flat_fonctions-metiers-propre-a-mon-api_2.Rmd: do not edit by hand

library(testthat)
test_that("say_hello works", {
  expect_equal(object = say_hello(personne="Sarah"),
               expected = "Hey coucou Sarah")
})

