# WARNING - Generated by {fusen} from /dev/flat_fonctions-metiers-propre-a-mon-api_2.Rmd: do not edit by hand

#' fonctions_metiers_propre_a_mon_api Title
#'
# comme ma fonction dépend de la fonction glue du pkg glue: il faut le signaler en:
#mettant la sourie à l'interieur de la fonction puis en allant dans
#Code -> insert Roxygène Skeleton
# en ajoutant @importFrom pkg name function name

#' Title: say hello
#'
#' @param personne la personne a qui on veut dire bjr
#' @importFrom glue glue
#' @return character de type "Hey coucou {personne}"
#' @export
#' @examples
#' say_hello(personne="Sarah")
#' say_hello(personne="Tchu")
say_hello=function(personne){
 glue("Hey coucou {personne}")
}
